### PR TITLE
Add relative flag support

### PR DESCRIPTION
**Pull request by DVDAndroid**
Added relative flag support `--relative` to support relative paths instead of absolute ones.

The default value is `false`, but in my opinion, it should be `true` since I don't want to see absolute path (ex: `/home/github/actions/...`) in my Github Actions logs

### CODE REVIEW

**Comment by DVDAndroid** [comment]
@renatoabreu11 sorry for bothering you, can you take a look at this? There are many PRs open

**Comment by renatoabreu11** [comment]
> @renatoabreu11 sorry for bothering you, can you take a look at this? There are many PRs open

Hey @DVDAndroid. No problem at all, I will take a look!
Sorry to take so long, I didn't receive a notification

**Comment by DVDAndroid** [comment]
Will the default value of `relative` change? I think people don't want to see internal Github Actions path (ex: `/home/github/actions`) in logs

**Comment by renatoabreu11** [comment]
> Will the default value of `relative` change? I think people don't want to see internal Github Actions path (ex: `/home/github/actions`) in logs

Yes, I agree with you. I will make the change as well 👍

**Pull request merged**
